language: node_js
install:
- git config --global user.email "hefangshi@gmail.com"
- git config --global user.name "hefangshi"
- npm install -g fis
- npm install -g fis-postpackager-autoload
- npm install -g fis-parser-less
- npm install -g fis-deploy-git
script: fis release -Dd ghpages
branches:
  only:
  - master
cache:
  directories:
  - "/home/travis/.nvm/v0.10.35/lib/node_modules"
env:
  global:
    secure: LVFfYoJsVtEY6BOJX5SqllKfYJUW9M1zQBmbcsdRU7tvwtbh3JEk80Xh94WUDkFHU3NoauXxMvYRTd8incXcekmDdSJeBFZLvvL956fWYawjFThW/LryddyQSmPWGmv/XivFgngezQPF/DBTouyx9JpSWtRe/C2NsJamqMDyZrk=
